version: "3.4"
services:
  vitets-excel-reader:
    image: node:18-alpine
    container_name: vitets-excel-reader
    entrypoint: /bin/sh
    ports: 
      - 8080:8080
    working_dir: /src/app
    volumes:
      - type: bind
        source: ./
        target: /src/app
    tty: true
    stdin_open: true
